version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ACCOUNT_ID: 978364619388
    ECR_REPO: user-service
    IMAGE_TAG: 0.0.2-SNAPSHOT
    GITHUB_TOKEN: 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

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Starting pre-build phase..."

      # Clone private GitHub repo using PAT from Secrets Manager
      - echo "Cloning private GitHub repository..."
      - git clone https://$GITHUB_TOKEN@github.com/username/private-repo.git
      - cd $PROJECT_DIR

      - echo "Moving to user-service directory"
      - cd user-service
      - mvn -v

      - echo "Building Spring Boot JAR"
      - mvn clean package -DskipTests

      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $ECR_REPO:$IMAGE_TAG .

      - echo "Tagging image"
      - docker tag $ECR_REPO:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - docker tag $ECR_REPO:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing images to ECR"
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

      - echo "Build completed successfully"
